services: docker
language: node_js

before_script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/cyber-dojo/master/shared/push_and_trigger.sh
    - chmod +x push_and_trigger.sh

script:
    # pull images used in tests so test-duration does not include pull time
    - docker pull cyberdojofoundation/ruby_mini_test:latest  # stateless
    - docker pull cyberdojofoundation/ruby_rspec:latest      # stateful
    - docker pull cyberdojofoundation/ruby_test_unit:latest  # processful

    #
    - echo "Building starter"
    - git clone https://github.com/cyber-dojo/starter.git
    - cd starter
    - git checkout api-for-new-web-ux
    - ./sh/build_docker_images.sh
    - cd ..

    #
    - ./pipe_build_up_test.sh \
        && ./push_and_trigger.sh cyber-dojo/commander
