
version: '2.2'

services:

  web:
    build:
      context: .
      args:
        - CYBER_DOJO_HOME=${CYBER_DOJO_HOME}
    user: nobody
    image: cyberdojo/web
    init: true
    container_name: test_cyber-dojo-web
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    volumes:
      - ./test:${CYBER_DOJO_HOME}/test:ro
    environment:
      - CYBER_DOJO_HOME
    depends_on:
      - differ
      - runner_stateless
      - runner_stateful
      - runner_processful
      - starter
      - storer
      - zipper

  # - - - - - - - - - - - - - - - -

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: test_web_cyber-dojo-starter
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: 'no'
    environment:
      - CYBER_DOJO_START_POINTS_ROOT
    volumes:
      - ./test_start_points:${CYBER_DOJO_START_POINTS_ROOT}:ro

  # - - - - - - - - - - - - - - - -

  storer:
    user: storer
    image: cyberdojo/storer
    init: true
    container_name: test_web_cyber-dojo-storer
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    environment:
      - CYBER_DOJO_KATAS_ROOT
    depends_on:
      - starter

  # - - - - - - - - - - - - - - - -

  runner_stateless:
    user: root
    image: cyberdojo/runner_stateless
    init: true
    container_name: test_web_cyber-dojo-runner-stateless
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  runner_stateful:
    user: root
    image: cyberdojo/runner_stateful
    init: true
    container_name: test_web_cyber-dojo-runner-stateful
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  runner_processful:
    user: root
    image: cyberdojo/runner_processful
    init: true
    container_name: test_web_cyber-dojo-runner-processful
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  differ:
    user: nobody
    image: cyberdojo/differ
    init: true
    container_name: test_web_cyber-dojo-differ
    read_only: true
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  zipper:
    user: nobody
    image: cyberdojo/zipper
    init: true
    container_name: test_web_cyber-dojo-zipper
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: 'no'
    depends_on:
      - storer
