
version: '3.7'

networks:
  cyber-dojo:
    driver: bridge
    name: cyber-dojo

services:

  web:
    depends_on:
      - avatars
      - differ
      - repler
      - runner
      - saver
      - shas
      - custom-start-points
      - exercises-chooser
      - languages-chooser

  # - - - - - - - - - - - - - - - -
  creator:
    depends_on:
      - saver
      - puller

  # - - - - - - - - - - - - - - - -
  exercises-chooser:
    depends_on:
      - exercises-start-points

  languages-chooser:
    depends_on:
      - languages-start-points
      - creator
