
version: '3.7'

networks:
  cyber-dojo:
    driver: bridge
    name: cyber-dojo

services:

  web:
    build:
      context: .
      args: [ COMMIT_SHA ]
    image: ${CYBER_DOJO_WEB_IMAGE}
    user: nobody
    container_name: test_web
    ports: [ "${CYBER_DOJO_WEB_PORT}:${CYBER_DOJO_WEB_PORT}" ]
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  creator:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_CREATOR_IMAGE}:${CYBER_DOJO_CREATOR_TAG}
    user: nobody
    container_name: test_web_creator
    read_only: true
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  exercises-chooser:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_EXERCISES_CHOOSER_IMAGE}:${CYBER_DOJO_EXERCISES_CHOOSER_TAG}
    user: nobody
    container_name: test_web_exercises_chooser
    ports: [ "${CYBER_DOJO_EXERCISES_CHOOSER_PORT}:${CYBER_DOJO_EXERCISES_CHOOSER_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp

  languages-chooser:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_LANGUAGES_CHOOSER_IMAGE}:${CYBER_DOJO_LANGUAGES_CHOOSER_TAG}
    user: nobody
    container_name: test_web_languages_chooser
    ports: [ "${CYBER_DOJO_LANGUAGES_CHOOSER_PORT}:${CYBER_DOJO_LANGUAGES_CHOOSER_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp

  # - - - - - - - - - - - - - - - -
  custom-start-points:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_CUSTOM_START_POINTS_IMAGE}:${CYBER_DOJO_CUSTOM_START_POINTS_TAG}
    user: nobody
    container_name: test_web_custom_start_points
    read_only: true
    ports: [ "${CYBER_DOJO_CUSTOM_START_POINTS_PORT}:${CYBER_DOJO_CUSTOM_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  exercises-start-points:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_EXERCISES_START_POINTS_IMAGE}:${CYBER_DOJO_EXERCISES_START_POINTS_TAG}
    user: nobody
    container_name: test_web_exercises_start_points
    read_only: true
    ports: [ "${CYBER_DOJO_EXERCISES_START_POINTS_PORT}:${CYBER_DOJO_EXERCISES_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  languages-start-points:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_LANGUAGES_START_POINTS_IMAGE}:${CYBER_DOJO_LANGUAGES_START_POINTS_TAG}
    user: nobody
    container_name: test_web_languages_start_points
    read_only: true
    ports: [ "${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}:${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  avatars:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_AVATARS_IMAGE}:${CYBER_DOJO_AVATARS_TAG}
    user: nobody
    container_name: test_web_avatars
    read_only: true
    ports: [ "${CYBER_DOJO_AVATARS_PORT}:${CYBER_DOJO_AVATARS_PORT}" ]
    restart: 'no'
    tmpfs: /tmp

  # - - - - - - - - - - - - - - - -
  repler:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_REPLER_IMAGE}:${CYBER_DOJO_REPLER_TAG}
    user: root
    container_name: test_web_repler
    read_only: true
    ports: [ "${CYBER_DOJO_REPLER_PORT}:${CYBER_DOJO_REPLER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    networks:
      - cyber-dojo
      - default

  # - - - - - - - - - - - - - - - -
  runner:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    user: root
    container_name: test_web_runner
    read_only: true
    ports: [ "${CYBER_DOJO_RUNNER_PORT}:${CYBER_DOJO_RUNNER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  # - - - - - - - - - - - - - - - -
  puller:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_PULLER_IMAGE}:${CYBER_DOJO_PULLER_TAG}
    user: root
    container_name: test_web_puller
    read_only: true
    ports: [ "${CYBER_DOJO_PULLER_PORT}:${CYBER_DOJO_PULLER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  # - - - - - - - - - - - - - - - -
  saver:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
    user: root
    container_name: test_web_saver
    read_only: true
    ports: [ "${CYBER_DOJO_SAVER_PORT}:${CYBER_DOJO_SAVER_PORT}" ]
    restart: 'no'
    tmpfs: [ "/cyber-dojo:uid=19663,gid=65533", "/tmp:uid=19663,gid=65533" ]

  # - - - - - - - - - - - - - - - -
  shas:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_SHAS_IMAGE}:${CYBER_DOJO_SHAS_TAG}
    user: nobody
    container_name: test_web_shas
    read_only: true
    ports: [ "${CYBER_DOJO_SHAS_PORT}:${CYBER_DOJO_SHAS_PORT}" ]
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  differ:
    environment: [ NO_PROMETHEUS=true ]
    image: ${CYBER_DOJO_DIFFER_IMAGE}:${CYBER_DOJO_DIFFER_TAG}
    user: nobody
    container_name: test_web_differ
    read_only: true
    ports: [ "${CYBER_DOJO_DIFFER_PORT}:${CYBER_DOJO_DIFFER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
