
version: '2.2'

services:

  web:
    build:
      context: .
      args:
        - SHA
    user: nobody
    image: cyberdojo/web
    init: true
    container_name: test-web
    volumes:
      - ./test:/cyber-dojo/test:ro
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    depends_on:
      - custom
      - differ
      - exercises
      - languages
      - mapper
      - ragger
      - runner
      - saver
      - zipper

  # - - - - - - - - - - - - - - - -

  custom:
    user: nobody
    image: cyberdojo/custom
    init: true
    container_name: test-web-custom
    read_only: true
    ports:
      - 4526:4526
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  exercises:
    user: nobody
    image: cyberdojo/exercises
    init: true
    container_name: test-web-exercises
    read_only: true
    ports:
      - 4525:4525
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  languages:
    user: nobody
    image: cyberdojo/languages-all
    init: true
    container_name: test-web-languages
    read_only: true
    ports:
      - 4524:4524
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  ragger:
    user: nobody
    image: cyberdojo/ragger
    init: true
    container_name: test-web-ragger
    read_only: true
    ports:
      - 5537:5537
    restart: 'no'
    depends_on:
      - runner
    tmpfs: /tmp

  # - - - - - - - - - - - - - - - -

  runner:
    user: root
    image: cyberdojo/runner-stateless
    init: true
    container_name: test-web-runner
    read_only: true
    ports:
      - 4597:4597
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  saver:
    user: saver
    image: cyberdojo/saver
    init: true
    container_name: test-web-saver
    read_only: true
    ports:
      - 4537:4537
    restart: 'no'
    depends_on:
      - mapper
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533

  # - - - - - - - - - - - - - - - -

  mapper:
    user: nobody
    image: cyberdojo/mapper
    init: true
    container_name: test-web-mapper
    read_only: true
    ports:
      - 4547:4547
    restart: 'no'
    tmpfs:
      - /tmp:uid=65534,gid=65533
    volumes:
      - ./test/data/porter:/porter:ro

  # - - - - - - - - - - - - - - - -

  differ:
    user: nobody
    image: cyberdojo/differ
    init: true
    container_name: test-web-differ
    read_only: true
    ports:
      - 4567:4567
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  zipper:
    user: nobody
    image: cyberdojo/zipper
    init: true
    container_name: test-web-zipper
    read_only: true
    ports:
      - 4587:4587
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - saver
