
version: '3.7'

networks:
  cyber-dojo:
    driver: bridge
    name: cyber-dojo

services:

  nginx:
    image: ${CYBER_DOJO_NGINX_IMAGE}:${CYBER_DOJO_NGINX_TAG}
    depends_on:
      - web
    user: root
    init: true
    container_name: test_web_nginx
    ports: [ "${CYBER_DOJO_NGINX_PORT}:80" ]
    restart: "no"

  # - - - - - - - - - - - - - - - -
  web:
    build:
      context: .
      args: [ COMMIT_SHA ]
    depends_on:
      - avatars
      - creator
      - differ
      - repler
      - runner
      - saver
      - shas
      - custom-chooser
      - exercises-chooser
      - languages-chooser
    user: nobody
    image: ${CYBER_DOJO_WEB_IMAGE}
    init: true
    container_name: test_web
    ports: [ "${CYBER_DOJO_WEB_PORT}:${CYBER_DOJO_WEB_PORT}" ]
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  creator:
  creator:
    depends_on:
      - saver
    user: nobody
    image: ${CYBER_DOJO_CREATOR_IMAGE}:${CYBER_DOJO_CREATOR_TAG}
    init: true
    container_name: test_web_creator
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  custom-chooser:
    depends_on:
      - custom-start-points
      - creator
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_CUSTOM_CHOOSER_IMAGE}:${CYBER_DOJO_CUSTOM_CHOOSER_TAG}
    init: true
    container_name: test_web_custom_chooser
    ports: [ "${CYBER_DOJO_CUSTOM_CHOOSER_PORT}:${CYBER_DOJO_CUSTOM_CHOOSER_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody

  exercises-chooser:
    depends_on:
      - exercises-start-points
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_EXERCISES_CHOOSER_IMAGE}:${CYBER_DOJO_EXERCISES_CHOOSER_TAG}
    init: true
    container_name: test_web_exercises_chooser
    ports: [ "${CYBER_DOJO_EXERCISES_CHOOSER_PORT}:${CYBER_DOJO_EXERCISES_CHOOSER_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody

  languages-chooser:
    depends_on:
      - languages-start-points
      - creator
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_LANGUAGES_CHOOSER_IMAGE}:${CYBER_DOJO_LANGUAGES_CHOOSER_TAG}
    init: true
    container_name: test_web_languages_chooser
    ports: [ "${CYBER_DOJO_LANGUAGES_CHOOSER_PORT}:${CYBER_DOJO_LANGUAGES_CHOOSER_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody

  # - - - - - - - - - - - - - - - -
  custom-start-points:
    user: root
    image: ${CYBER_DOJO_CUSTOM_START_POINTS_IMAGE}:${CYBER_DOJO_CUSTOM_START_POINTS_TAG}
    init: true
    container_name: test_web_custom_start_points
    environment: [ NO_PROMETHEUS, NO_IMAGE_PULLS ]
    read_only: true
    ports: [ "${CYBER_DOJO_CUSTOM_START_POINTS_PORT}:${CYBER_DOJO_CUSTOM_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  exercises-start-points:
    user: root
    image: ${CYBER_DOJO_EXERCISES_START_POINTS_IMAGE}:${CYBER_DOJO_EXERCISES_START_POINTS_TAG}
    init: true
    container_name: test_web_exercises_start_points
    environment: [ NO_PROMETHEUS, NO_IMAGE_PULLS ]
    read_only: true
    ports: [ "${CYBER_DOJO_EXERCISES_START_POINTS_PORT}:${CYBER_DOJO_EXERCISES_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  languages-start-points:
    user: root
    image: cyberdojo/languages-start-points-all:${CYBER_DOJO_LANGUAGES_START_POINTS_TAG} # tests need -all
    init: true
    container_name: test_web_languages_start_points
    environment: [ NO_PROMETHEUS, NO_IMAGE_PULLS ]
    read_only: true
    ports: [ "${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}:${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  # - - - - - - - - - - - - - - - -
  avatars:
    user: nobody
    image: ${CYBER_DOJO_AVATARS_IMAGE}:${CYBER_DOJO_AVATARS_TAG}
    init: true
    container_name: test_web_avatars
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_AVATARS_PORT}:${CYBER_DOJO_AVATARS_PORT}" ]
    restart: 'no'
    tmpfs: /tmp

  # - - - - - - - - - - - - - - - -
  repler:
    user: root
    image: ${CYBER_DOJO_REPLER_IMAGE}:${CYBER_DOJO_REPLER_TAG}
    init: true
    container_name: test_web_repler
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_REPLER_PORT}:${CYBER_DOJO_REPLER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    networks:
      - cyber-dojo
      - default

  # - - - - - - - - - - - - - - - -
  runner:
    user: root
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    init: true
    container_name: test_web_runner
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_RUNNER_PORT}:${CYBER_DOJO_RUNNER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  # - - - - - - - - - - - - - - - -
  saver:
    user: root
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
    init: true
    container_name: test_web_saver
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_SAVER_PORT}:${CYBER_DOJO_SAVER_PORT}" ]
    restart: 'no'
    tmpfs: [ "/cyber-dojo:uid=19663,gid=65533", "/tmp:uid=19663,gid=65533" ]

  # - - - - - - - - - - - - - - - -
  shas:
    user: nobody
    image: ${CYBER_DOJO_SHAS_IMAGE}:${CYBER_DOJO_SHAS_TAG}
    init: true
    container_name: test_web_shas
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_SHAS_PORT}:${CYBER_DOJO_SHAS_PORT}" ]
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  differ:
    user: nobody
    image: ${CYBER_DOJO_DIFFER_IMAGE}:${CYBER_DOJO_DIFFER_TAG}
    init: true
    container_name: test_web_differ
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_DIFFER_PORT}:${CYBER_DOJO_DIFFER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
