
version: '2.2'

services:

  web:
    build:
      context: .
      args:
        - ALPINE_VERSION
        - WEB_HOME
        - SHA
    user: nobody
    image: cyberdojo/web
    init: true
    container_name: test-cyber-dojo-web
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    depends_on:
      - differ
      - runner-stateful
      - runner-stateless
      - starter
      - storer
      - zipper

  # - - - - - - - - - - - - - - - -

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: test-web-cyber-dojo-starter
    expose: [ "${STARTER_SERVICE_PORT}" ]
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: 'no'
    environment:
      - STARTER_SERVICE_PORT
      - START_POINTS_ROOT
    volumes:
      - ./test/data/start_points:${START_POINTS_ROOT}:ro

  # - - - - - - - - - - - - - - - -

  storer:
    user: storer
    image: cyberdojo/storer
    init: true
    container_name: test-web-cyber-dojo-storer
    read_only: true
    tmpfs: /tmp
    volumes:
      - /tmp:/usr/src/cyber-dojo/katas:rw
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    depends_on:
      - starter

  # - - - - - - - - - - - - - - - -

  runner-stateless:
    user: root
    image: cyberdojo/runner-stateless
    init: true
    container_name: test-web-cyber-dojo-runner-stateless
    expose: [ "${RUNNER_STATELESS_SERVICE_PORT}" ]
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    environment:
      - RUNNER_STATELESS_SERVICE_PORT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  runner-stateful:
    user: root
    image: cyberdojo/runner-stateful
    init: true
    container_name: test-web-cyber-dojo-runner-stateful
    expose: [ "${RUNNER_STATEFUL_SERVICE_PORT}" ]
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    environment:
      - RUNNER_STATEFUL_SERVICE_PORT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  differ:
    user: nobody
    image: cyberdojo/differ
    init: true
    container_name: test-web-cyber-dojo-differ
    expose: [ "${DIFFER_SERVICE_PORT}" ]
    read_only: true
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: 'no'
    environment:
      - DIFFER_SERVICE_PORT

  # - - - - - - - - - - - - - - - -

  zipper:
    user: nobody
    image: cyberdojo/zipper
    init: true
    container_name: test-web-cyber-dojo-zipper
    expose: [ "${ZIPPER_SERVICE_PORT}" ]
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: 'no'
    environment:
      - ZIPPER_SERVICE_PORT
      - STORER_SERVICE_PORT
    depends_on:
      - storer
