
version: '2.2'

services:

  web:
    build:
      context: .
      args:
        - SHA
    user: nobody
    image: cyberdojo/web
    init: true
    container_name: test-web
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    depends_on:
      - starter
      - runner
      - saver
      - differ
      - zipper

  # - - - - - - - - - - - - - - - -

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: test-web-starter
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - ./test/data/start_points:/app/start_points:ro

  # - - - - - - - - - - - - - - - -

  runner:
    user: root
    image: cyberdojo/runner-stateless
    init: true
    container_name: test-web-runner
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  saver:
    user: saver
    image: cyberdojo/saver
    init: true
    container_name: test-web-saver
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /tmp/groups/:/groups:rw
      - /tmp/katas/:/katas:rw

  # - - - - - - - - - - - - - - - -

  differ:
    user: nobody
    image: cyberdojo/differ
    init: true
    container_name: test-web-differ
    read_only: true
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  zipper:
    user: nobody
    image: cyberdojo/zipper
    init: true
    container_name: test-web-zipper
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - saver
