
version: '3.7'

services:

  web:
    build:
      context: .
      args: [ COMMIT_SHA ]
    user: nobody
    image: ${CYBER_DOJO_WEB_IMAGE}
    init: true
    container_name: test-web
    ports: [ "${CYBER_DOJO_WEB_PORT}:${CYBER_DOJO_WEB_PORT}" ]
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  creator:
    user: nobody
    image: ${CYBER_DOJO_CREATOR_IMAGE}:${CYBER_DOJO_CREATOR_TAG}
    init: true
    container_name: test-web-creator
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  custom-start-points:
    user: nobody
    image: ${CYBER_DOJO_CUSTOM_START_POINTS_IMAGE}:${CYBER_DOJO_CUSTOM_START_POINTS_TAG}
    init: true
    container_name: test-web-custom-start-points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_CUSTOM_START_POINTS_PORT}:${CYBER_DOJO_CUSTOM_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  exercises-start-points:
    user: nobody
    image: ${CYBER_DOJO_EXERCISES_START_POINTS_IMAGE}:${CYBER_DOJO_EXERCISES_START_POINTS_TAG}
    init: true
    container_name: test-web-exercises-start-points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_EXERCISES_START_POINTS_PORT}:${CYBER_DOJO_EXERCISES_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  languages-start-points:
    user: nobody
    image: cyberdojo/languages-start-points-all:${CYBER_DOJO_LANGUAGES_START_POINTS_TAG} # tests need -all
    init: true
    container_name: test-web-languages-start-points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}:${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  avatars:
    user: nobody
    image: ${CYBER_DOJO_AVATARS_IMAGE}:${CYBER_DOJO_AVATARS_TAG}
    init: true
    container_name: test-web-avatars
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_AVATARS_PORT}:${CYBER_DOJO_AVATARS_PORT}" ]
    restart: 'no'
    tmpfs: /tmp

  # - - - - - - - - - - - - - - - -
  runner:
    user: root
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    init: true
    container_name: test-web-runner
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_RUNNER_PORT}:${CYBER_DOJO_RUNNER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  # - - - - - - - - - - - - - - - -
  saver:
    user: saver
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
    init: true
    container_name: test-web-saver
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_SAVER_PORT}:${CYBER_DOJO_SAVER_PORT}" ]
    restart: 'no'
    tmpfs: [ "/cyber-dojo:uid=19663,gid=65533", "/tmp:uid=19663,gid=65533" ]

  # - - - - - - - - - - - - - - - -
  differ:
    user: nobody
    image: ${CYBER_DOJO_DIFFER_IMAGE}:${CYBER_DOJO_DIFFER_TAG}
    init: true
    container_name: test-web-differ
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_DIFFER_PORT}:${CYBER_DOJO_DIFFER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  zipper:
    user: nobody
    image: ${CYBER_DOJO_ZIPPER_IMAGE}:${CYBER_DOJO_ZIPPER_TAG}
    init: true
    container_name: test-web-zipper
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_ZIPPER_PORT}:${CYBER_DOJO_ZIPPER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    depends_on: [ saver ]
