
version: '2.2'

services:

  web:
    build:
      context: .
      args:
        - SHA
    user: nobody
    image: cyberdojo/web
    init: true
    container_name: test-web
    mem_limit: 2G
    memswap_limit: 2G
    restart: 'no'
    depends_on:
      - starter
      - runner
      - saver
      - differ
      - zipper

  # - - - - - - - - - - - - - - - -

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: test-web-starter
    ports:
      - 4527:4527
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - ./test/data/start_points:/app/start_points:ro

  # - - - - - - - - - - - - - - - -

  runner:
    user: root
    image: cyberdojo/runner-stateless
    init: true
    container_name: test-web-runner
    read_only: true
    ports:
      - 4597:4597
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  saver:
    user: saver
    image: cyberdojo/saver
    init: true
    container_name: test-web-saver
    read_only: true
    ports:
      - 4537:4537
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - ported
    tmpfs:
      - /cyber-dojo:uid=19663,gid=19663
      - /tmp:uid=19663,gid=19663

  # - - - - - - - - - - - - - - - -

  ported:
    user: nobody
    image: cyberdojo/ported
    init: true
    container_name: test-web-ported
    read_only: true
    ports:
      - 4547:4547
    tmpfs: /tmp
    restart: 'no'
    tmpfs:
      - /porter:uid=65534,gid=65533
      - /tmp:uid=65534,gid=65533

  # - - - - - - - - - - - - - - - -

  differ:
    user: nobody
    image: cyberdojo/differ
    init: true
    container_name: test-web-differ
    read_only: true
    ports:
      - 4567:4567
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  zipper:
    user: nobody
    image: cyberdojo/zipper
    init: true
    container_name: test-web-zipper
    read_only: true
    ports:
      - 4587:4587
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - saver
