
version: '2.2'

services:

  web:
    build:
      context: .
      args:
        - SHA
    user: nobody
    image: cyberdojo/web
    init: true
    container_name: test-web
    restart: 'no'
    depends_on:
      - avatars
      - custom-start-points
      - exercises
      - exercises-start-points
      - languages
      - differ
      - ragger
      - runner
      - saver
      - zipper

  # - - - - - - - - - - - - - - - -

  custom-start-points:
    user: nobody
    image: cyberdojo/custom-start-points:latest # TODO: ${CYBER_DOJO_CUSTOM}
    init: true
    container_name: test-web-custom-start-points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 4526:4526
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  exercises:
    user: nobody
    image: ${CYBER_DOJO_EXERCISES}
    init: true
    container_name: test-web-exercises
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 4999:4999
    tmpfs: /tmp
    restart: 'no'

  exercises-start-points:
    user: nobody
    image: cyberdojo/exercises-start-points:latest
    init: true
    container_name: test-web-exercises-start-points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 4535:4535
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  languages:
    user: nobody
    image: ${CYBER_DOJO_LANGUAGES}
    init: true
    container_name: test-web-languages
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 4524:4524
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  avatars:
    user: nobody
    image: cyberdojo/avatars:${CYBER_DOJO_AVATARS_TAG}
    init: true
    container_name: test-web-avatars
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 5027:5027
    restart: 'no'
    tmpfs: /tmp

  # - - - - - - - - - - - - - - - -

  ragger:
    user: nobody
    image: cyberdojo/ragger:${CYBER_DOJO_RAGGER_TAG}
    init: true
    container_name: test-web-ragger
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 5537:5537
    restart: 'no'
    depends_on:
      - runner
    tmpfs: /tmp

  # - - - - - - - - - - - - - - - -

  runner:
    user: root
    image: cyberdojo/runner:${CYBER_DOJO_RUNNER_TAG}
    init: true
    container_name: test-web-runner
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 4597:4597
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - -

  saver:
    user: saver
    image: cyberdojo/saver:${CYBER_DOJO_SAVER_TAG}
    init: true
    container_name: test-web-saver
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 4537:4537
    restart: 'no'
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533

  # - - - - - - - - - - - - - - - -

  differ:
    user: nobody
    image: cyberdojo/differ:${CYBER_DOJO_DIFFER_TAG}
    init: true
    container_name: test-web-differ
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 4567:4567
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -

  zipper:
    user: nobody
    image: cyberdojo/zipper:${CYBER_DOJO_ZIPPER_TAG}
    init: true
    container_name: test-web-zipper
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports:
      - 4587:4587
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - saver
