
version: '3.7'

networks:
  cyber-dojo:
    driver: bridge
    name: cyber-dojo

services:
  web:
    build:
      context: .
      args: [ COMMIT_SHA ]
    user: nobody
    image: ${CYBER_DOJO_WEB_IMAGE}
    init: true
    container_name: test_web
    ports: [ "${CYBER_DOJO_WEB_PORT}:${CYBER_DOJO_WEB_PORT}" ]
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  creator:
    user: nobody
    image: ${CYBER_DOJO_CREATOR_IMAGE}:${CYBER_DOJO_CREATOR_TAG}
    init: true
    container_name: test_web_creator
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    tmpfs: /tmp
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  custom-start-points:
    user: root
    image: ${CYBER_DOJO_CUSTOM_START_POINTS_IMAGE}:${CYBER_DOJO_CUSTOM_START_POINTS_TAG}
    init: true
    container_name: test_web_custom_start_points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_CUSTOM_START_POINTS_PORT}:${CYBER_DOJO_CUSTOM_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  exercises-start-points:
    user: root
    image: ${CYBER_DOJO_EXERCISES_START_POINTS_IMAGE}:${CYBER_DOJO_EXERCISES_START_POINTS_TAG}
    init: true
    container_name: test_web_exercises_start_points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_EXERCISES_START_POINTS_PORT}:${CYBER_DOJO_EXERCISES_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  languages-start-points:
    user: root
    image: cyberdojo/languages-start-points-all:${CYBER_DOJO_LANGUAGES_START_POINTS_TAG} # tests need -all
    init: true
    container_name: test_web_languages_start_points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}:${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  # - - - - - - - - - - - - - - - -
  avatars:
    user: nobody
    image: ${CYBER_DOJO_AVATARS_IMAGE}:${CYBER_DOJO_AVATARS_TAG}
    init: true
    container_name: test_web_avatars
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_AVATARS_PORT}:${CYBER_DOJO_AVATARS_PORT}" ]
    restart: 'no'
    tmpfs: /tmp

  # - - - - - - - - - - - - - - - -
  repler:
    user: root
    image: ${CYBER_DOJO_REPLER_IMAGE}:${CYBER_DOJO_REPLER_TAG}
    init: true
    container_name: test_web_repler
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_REPLER_PORT}:${CYBER_DOJO_REPLER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    networks:
      - cyber-dojo
      - default

  # - - - - - - - - - - - - - - - -
  runner:
    user: root
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    init: true
    container_name: test_web_runner
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_RUNNER_PORT}:${CYBER_DOJO_RUNNER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]

  # - - - - - - - - - - - - - - - -
  saver:
    user: saver
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
    init: true
    container_name: test_web_saver
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_SAVER_PORT}:${CYBER_DOJO_SAVER_PORT}" ]
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  shas:
    user: nobody
    image: ${CYBER_DOJO_SHAS_IMAGE}:${CYBER_DOJO_SHAS_TAG}
    init: true
    container_name: test_web_shas
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_SHAS_PORT}:${CYBER_DOJO_SHAS_PORT}" ]
    restart: 'no'

  # - - - - - - - - - - - - - - - -
  differ:
    user: nobody
    image: ${CYBER_DOJO_DIFFER_IMAGE}:${CYBER_DOJO_DIFFER_TAG}
    init: true
    container_name: test_web_differ
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_DIFFER_PORT}:${CYBER_DOJO_DIFFER_PORT}" ]
    tmpfs: /tmp
    restart: 'no'
