
fullnameOverride: "web"

replicaCount: 1

envFromSecret: {}
nodeSelector: {}
affinity: {}
tolerations: []

podSecurityContext:
  fsGroup: 65534 # nobody

service:
  port: 3000

containers:
  - name: web
    securityContext:
      runAsUser: 65534 # nobody
      allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 768Mi
    #livenessProbe:
    #  path: /alive?
    #  port: 3000
    #readinessProbe:
    #  path: /ready?
    #  port: 3000
