
fullnameOverride: "web"

replicaCount: 2

envFromSecret: {}
nodeSelector: {}
affinity: {}
tolerations: []

podSecurityContext:
  fsGroup: 65534 # nobody

# Probes
#- - - - - -
# If you comment out the live/ready probe lines below
# make sure to edit deploy_to_namespace.sh so it calls
# helm_upgrade_probe_no_prometheus_no()

containers:
  - name: web
    securityContext:
      runAsUser: 65534 # nobody
      allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 768Mi
    livenessProbe:
      path: /alive?
    readinessProbe:
      path: /ready?
