
fullnameOverride: "web"

replicaCount: 2

envFromSecret: {}
nodeSelector: {}
affinity: {}
tolerations: []

podSecurityContext:
  fsGroup: 65534 # nobody

# Probes
#- - - - - -
# If you append this to yml below make sure to edit
# deploy_to_namespace.sh so it calls
# helm_upgrade_probe_yes_prometheus_no()
#
#containers:
#  - name: web
#    livenessProbe:
#      path: /alive?
#    readinessProbe:
#      path: /ready?

containers:
  - name: web
    securityContext:
      runAsUser: 65534 # nobody
      allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 768Mi
