
fullnameOverride: "web"

replicaCount: 3

service:
  port: 3000

containers:
  - name: web
    image: cyberdojo/web
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
    #livenessProbe:
    #  path: /alive?
    #  port: 3000
    #readinessProbe:
    #  path: /ready?
    #  port: 3000

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
