# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "web"

replicaCount: 1

service:
  port: 3000

containers:
  - name: web
    image: cyberdojo/web
    tag: ""
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 256Mi
      #livenessProbe:
      #  path: /sha
      #  port: 3000
      #readinessProbe:
      #  path: /ready?
      #  port: 3000

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
