# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# app name
fullnameOverride: "web"

# deployment spec
replicaCount: 1
 
       

# containers
# provide default values that you HAVE to overwrite in your values.yaml file
containers: 
  - name: web
    image: cyberdojo/web
    tag: "55a2328"  
    resources: 
      limits:
       memory: 1Gi
      requests:
       memory: 1Gi
    # livenessProbe:
    #   path: /health
    #   port: 80
    # readinessProbe:
    #   path: /health
    #   port: 80

envFromSecret: {}
 

nodeSelector: {}

affinity: {}

tolerations: []

# service
service: 
  port: 3000  
  
  
