
fullnameOverride: "web"

replicaCount: 3

service:
  port: 3000

containers:
  - name: web
    image: cyberdojo/web
    securityContext:
      runAsUser: 65534 # nobody
      fsGroup: 65534 # nobody
      allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    livenessProbe:
      path: /alive?
      port: 3000
    readinessProbe:
      path: /ready?
      port: 3000

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
